### ISSUE TITLE
[Llama 3B] Support for Prefill (decode on host)

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-forge-fe#127]

**Comment by dgolubovicTT** [comment]
@nvukobratTT is there a test for this?

**Comment by nvukobratTT** [comment]
> @nvukobratTT is there a test for this? 

There is no specific prefil tes, feel free to create one under tests/ directory. 

Currently, the main inference test is a close version of it. However, let's leave it for a full e2e demo ;))

**Comment by dgolubovicTT** [comment]
@nvukobratTT I have one more question about the issue. Since Llama attention is blocked due to metal issue https://github.com/tenstorrent/tt-metal/issues/13005 this prefil won't compile. All I can do is make the test that will fail and skip it. This is fine because as soon as attention is working, we will be able to push all Llama 3B issues including this one to the very end. The only question is do we want to check it in under pytest skip.

**Comment by nvukobratTT** [comment]
> @nvukobratTT I have one more question about the issue. Since Llama attention is blocked due to metal issue [tenstorrent/tt-metal#13005](https://github.com/tenstorrent/tt-metal/issues/13005) this prefil won't compile. All I can do is make the test that will fail and skip it. This is fine because as soon as attention is working, we will be able to push all Llama 3B issues including this one to the very end. The only question is do we want to check it in under pytest skip.

It's okay to create the text and mark it with skip. In this case, we can also mark it as xfail as it'll enable us to track failure messages if prefill regress over some other FFE/MLIR changes :))
