### ISSUE TITLE
[Ops] Decompose indexing op into regular matmul instead of SMM

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-forge-fe#172]
Baed on the details from this task:
- https://github.com/tenstorrent/tt-forge-fe/issues/121

**Comment by mbezuljTT** [comment]
I believe it should resolve it. 

to_layout should add padding. I'm still confused on where padding value is set. Some times padding value is important, like you need -inf when calculating max, or zero value at tensor that goes to matmul, or non zero value if doing eltwise division etc.

**Comment by nvukobratTT** [comment]
> I believe it should resolve it.
> 
> to_layout should add padding. I'm still confused on where padding value is set. Some times padding value is important, like you need -inf when calculating max, or zero value at tensor that goes to matmul, or non zero value if doing eltwise division etc.

Thanks! 

@dgolubovicTT we should get the following PR merged soon:
- https://github.com/tenstorrent/tt-mlir/pull/624

Once that's done, let's see if this issue is resolved.

**Comment by dgolubovicTT** [comment]
It seems like it is a runtime issue. In runtime runProgram method, all ttnn ops are executed, and then at the end of the method we get memory corruption: free(): invalid pointer (trying to deallocate).

**Comment by dgolubovicTT** [comment]
I talked with @pilkicTT and it turns out that we had padding of constant input (lhs of matmul), due to old logic from buda that padded all constants to tile size (since every tensor in buda had to be rounded to tile size). I tried the quick fix, and managed to get tests passing. I expect to send this on code review as soon as Pedja's changes land in main.

**Comment by dgolubovicTT** [comment]
I had one more test case failing due to transpose changing rank of tensor (3D -> 4D). This was because transpose runtime uses unsqueeze op to set tensor to 4D, but never returns it back to 3D. This is the PR on mlir side: [PR](https://github.com/tenstorrent/tt-mlir/pull/730). As soon as this is merged I will create PR for Indexing decompose.

Side note, is that currently Indexing decompose consists of one matmul and 2 transposes (if needed). When stride is 1 indexing could be simplified to some kind of select. However, select is still unsupported in MLIR. As soon as select is supported, I will follow up with the update of Indexing. Tracking issue: https://github.com/tenstorrent/tt-forge-fe/issues/299
