### ISSUE TITLE
Default IRD image doesn't contain ninja

### ISSUE THREAD

**Issue by sdjordjevicTT** [tenstorrent/tt-forge-fe#289]
It would be nice to have a dedicated docker image for forge-fe development...

**Comment by nvukobratTT** [comment]
@vmilosevic do you have a tracking issue for creating FFE docker as well? :)) 

If not, we can expand on top of this one :))

**Comment by vmilosevic** [comment]
There are now two flavors of IRC-compatible docker images, base and full. The base image contains only dependencies and the full image also contains a prebuilt toolchain to speed up things.

Working from IRD image

Start IRD with docker image:
```
ghcr.io/tenstorrent/tt-forge-fe/tt-forge-fe-ird-ubuntu-22-04:latest OR
ghcr.io/tenstorrent/tt-forge-fe/tt-forge-fe-base-ird-ubuntu-22-04:latest
```

```
git clone git@github.com:tenstorrent/tt-forge-fe.git
cd tt-forge-fe
git submodule update --init --recursive -f
source env/activate
cmake -B env/build env          # you need env build only with base image
cmake --build env/build         # you need env build only with base image
cmake -G Ninja -B build .
cmake --build build
pytest 
```

If you encounter any permission issues you should change ownership from root to your user
`sudo chown -R <user>:<group> /opt/ttforge-toolchain`
This will be fixed in the next docker image build

**Comment by vmilosevic** [comment]
https://github.com/tenstorrent/tt-forge-internal/wiki/Getting-Started#using-docker-images
